accueil_visitor:
    path:     /
    defaults: { _controller: ArenaFightBundle:Joueur:index }
joueur_quetes:
    path:     /quetes
    defaults: { _controller: ArenaFightBundle:Joueur:indexQuetes }
joueur_envoi_quete:
    path:     /envoiQuete
    defaults: { _controller: ArenaFightBundle:Joueur:envoiQuete }
joueur_accueil_persos:
    path:     /personnages
    defaults: { _controller: ArenaFightBundle:Joueur:accueilPersos }
joueur_ajouter_perso:
    path:     /ajouter-personnage
    defaults: { _controller: ArenaFightBundle:Joueur:ajouterPerso }    
