accueil_visitor:
    path:     /
    defaults: { _controller: ArenaFightBundle:Joueur:index }
joueur_profil:
    path:     /profil
    defaults: { _controller: ArenaFightBundle:Joueur:profil }     
joueur_quetes:
    path:     /quetes
    defaults: { _controller: ArenaFightBundle:Joueur:indexQuetes }
joueur_envoi_quete:
    path:     /envoiQuete
    defaults: { _controller: ArenaFightBundle:Joueur:envoiQuete }
joueur_accueil_persos:
    path:     /personnages
    defaults: { _controller: ArenaFightBundle:Joueur:accueilPersos }
joueur_ajouter_perso:
    path:     /ajouter-personnage
    defaults: { _controller: ArenaFightBundle:Joueur:ajouterPerso }
joueur_vue_supprimer_perso:
    path:     /selection-personnage-a-supprimer
    defaults: { _controller: ArenaFightBundle:Joueur:vueSupprimerPerso }
joueur_supprimer_perso:
    path:     /supprimer-personnage
    defaults: { _controller: ArenaFightBundle:Joueur:supprimerPerso }
joueur_equiper_perso:
    path:     /equiper-personnage
    defaults: { _controller: ArenaFightBundle:Joueur:equiperPerso }
joueur_desequiper_perso:
    path:     /desequiper-personnage
    defaults: { _controller: ArenaFightBundle:Joueur:desequiperPerso }    
