<?php

namespace ArenaFightBundle\Repository;

/**
 * LootItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LootItemRepository extends \Doctrine\ORM\EntityRepository
{
}
