<?php

namespace ArenaFightBundle\Repository;

/**
 * TypeItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeItemRepository extends \Doctrine\ORM\EntityRepository
{
}
