<?php

namespace Proxies\__CG__\ArenaFightBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Item extends \ArenaFightBundle\Entity\Item implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'id', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'nom', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'description', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'degats', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'reductionDegats', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'vitesse', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'regen', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'prix', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'levelMini', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'typeItem'];
        }

        return ['__isInitialized__', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'id', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'nom', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'description', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'degats', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'reductionDegats', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'vitesse', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'regen', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'prix', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'levelMini', '' . "\0" . 'ArenaFightBundle\\Entity\\Item' . "\0" . 'typeItem'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Item $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDegats($degats)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDegats', [$degats]);

        return parent::setDegats($degats);
    }

    /**
     * {@inheritDoc}
     */
    public function getDegats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDegats', []);

        return parent::getDegats();
    }

    /**
     * {@inheritDoc}
     */
    public function setReductionDegats($reductionDegats)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReductionDegats', [$reductionDegats]);

        return parent::setReductionDegats($reductionDegats);
    }

    /**
     * {@inheritDoc}
     */
    public function getReductionDegats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReductionDegats', []);

        return parent::getReductionDegats();
    }

    /**
     * {@inheritDoc}
     */
    public function setVitesse($vitesse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVitesse', [$vitesse]);

        return parent::setVitesse($vitesse);
    }

    /**
     * {@inheritDoc}
     */
    public function getVitesse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVitesse', []);

        return parent::getVitesse();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegen($regen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegen', [$regen]);

        return parent::setRegen($regen);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegen', []);

        return parent::getRegen();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setLevelMini($levelMini)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLevelMini', [$levelMini]);

        return parent::setLevelMini($levelMini);
    }

    /**
     * {@inheritDoc}
     */
    public function getLevelMini()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLevelMini', []);

        return parent::getLevelMini();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeItem(\ArenaFightBundle\Entity\TypeItem $typeItem = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeItem', [$typeItem]);

        return parent::setTypeItem($typeItem);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeItem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeItem', []);

        return parent::getTypeItem();
    }

}
